export const ROMANTIC_LOGS = [
  "> Booting KatiaOS v1.0...",
  "> Establishing secure connection to Oleg's heart...",
  "> Connecting to Katia's Heart Database... [OK]",
  "> Verifying Oleg's endless love credentials... [PASSED 100%]",
  "> Checking compatibility... [MATCH: 100%]",
  "> Scanning for red flags... [NONE FOUND]",
  "> Measuring how much she means to him... [OVERFLOW ERROR: value too large]",
  "> Fetching 1000+ reasons why Katia is loved... [OK]",
  "> Loading memories/first_date.jpg...",
  "> Loading memories/every_laugh.mp3...",
  "> Indexing inside jokes... [2,847 found]",
  "> Syncing favorite moments... [DONE]",
  "> Initializing Affection Protocol v2.0...",
  "> Calibrating hug strength... [MAX POWER]",
  "> Loading 'I miss you' notifications... [∞ pending]",
  "> Applying extra care module... [ACTIVE]",
  "> Preparing birthday surprise payload...",
  "> Wrapping gift.exe...",
  "> Adding a little more love just in case...",
  "> Compiling happiness.dll... [SUCCESS]",
  "> Running final checks... [ALL SYSTEMS GO]",
  "> Everything is ready! Opening Katia's space... ✨",
];